CREATE TABLE "batiment"();
SELECT AddGeometryColumn('batiment','geometrie',2154,'GEOMETRY',3);
CREATE INDEX "batiment_geometrie_geom_idx" ON "batiment" USING GIST ("geometrie");
ALTER TABLE "batiment" ADD COLUMN "cleabs" VARCHAR(24);
ALTER TABLE "batiment" ADD COLUMN "nature" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "usage_1" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "usage_2" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "construction_legere" BOOLEAN;
ALTER TABLE "batiment" ADD COLUMN "etat_de_l_objet" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "date_creation" timestamp with time zone;
ALTER TABLE "batiment" ADD COLUMN "date_modification" timestamp with time zone;
ALTER TABLE "batiment" ADD COLUMN "date_d_apparition" date;
ALTER TABLE "batiment" ADD COLUMN "date_de_confirmation" date;
ALTER TABLE "batiment" ADD COLUMN "sources" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "identifiants_sources" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "precision_planimetrique" NUMERIC(5,1);
ALTER TABLE "batiment" ADD COLUMN "precision_altimetrique" NUMERIC(5,1);
ALTER TABLE "batiment" ADD COLUMN "nombre_de_logements" INTEGER;
ALTER TABLE "batiment" ADD COLUMN "nombre_d_etages" INTEGER;
ALTER TABLE "batiment" ADD COLUMN "materiaux_des_murs" VARCHAR(2);
ALTER TABLE "batiment" ADD COLUMN "materiaux_de_la_toiture" VARCHAR(2);
ALTER TABLE "batiment" ADD COLUMN "hauteur" NUMERIC(7,1);
ALTER TABLE "batiment" ADD COLUMN "altitude_minimale_sol" NUMERIC(7,1);
ALTER TABLE "batiment" ADD COLUMN "altitude_minimale_toit" NUMERIC(7,1);
ALTER TABLE "batiment" ADD COLUMN "altitude_maximale_toit" NUMERIC(7,1);
ALTER TABLE "batiment" ADD COLUMN "altitude_maximale_sol" NUMERIC(7,1);
ALTER TABLE "batiment" ADD COLUMN "origine_du_batiment" VARCHAR;
ALTER TABLE "batiment" ADD COLUMN "appariement_fichiers_fonciers" VARCHAR(32);

