CREATE TABLE "commune"();
SELECT AddGeometryColumn('commune','geometrie',2154,'GEOMETRY',2);
CREATE INDEX "commune_geometrie_geom_idx" ON "commune" USING GIST ("geometrie");
ALTER TABLE "commune" ADD COLUMN "cleabs" VARCHAR(24);
ALTER TABLE "commune" ADD COLUMN "code_insee" VARCHAR(5);
ALTER TABLE "commune" ADD COLUMN "code_insee_de_l_arrondissement" VARCHAR(5);
ALTER TABLE "commune" ADD COLUMN "code_insee_de_la_collectivite_terr" VARCHAR(5);
ALTER TABLE "commune" ADD COLUMN "code_insee_du_departement" VARCHAR(5);
ALTER TABLE "commune" ADD COLUMN "code_insee_de_la_region" VARCHAR(5);
ALTER TABLE "commune" ADD COLUMN "population" INTEGER;
ALTER TABLE "commune" ADD COLUMN "surface_en_ha" INTEGER;
ALTER TABLE "commune" ADD COLUMN "date_creation" timestamp with time zone;
ALTER TABLE "commune" ADD COLUMN "date_modification" timestamp with time zone;
ALTER TABLE "commune" ADD COLUMN "date_d_apparition" date;
ALTER TABLE "commune" ADD COLUMN "date_de_confirmation" date;
ALTER TABLE "commune" ADD COLUMN "code_postal" VARCHAR(5);
ALTER TABLE "commune" ADD COLUMN "nom_officiel" VARCHAR;
ALTER TABLE "commune" ADD COLUMN "chef_lieu_d_arrondissement" BOOLEAN;
ALTER TABLE "commune" ADD COLUMN "chef_lieu_de_collectivite_terr" BOOLEAN;
ALTER TABLE "commune" ADD COLUMN "chef_lieu_de_departement" BOOLEAN;
ALTER TABLE "commune" ADD COLUMN "chef_lieu_de_region" BOOLEAN;
ALTER TABLE "commune" ADD COLUMN "capitale_d_etat" BOOLEAN;
ALTER TABLE "commune" ADD COLUMN "date_du_recensement" date;
ALTER TABLE "commune" ADD COLUMN "organisme_recenseur" VARCHAR(16);
ALTER TABLE "commune" ADD COLUMN "codes_siren_des_epci" VARCHAR(32);
ALTER TABLE "commune" ADD COLUMN "lien_vers_chef_lieu" VARCHAR(24);
ALTER TABLE "commune" ADD COLUMN "liens_vers_autorite_administrative" VARCHAR;
ALTER TABLE "commune" ADD COLUMN "code_siren" VARCHAR(9);

