CREATE TABLE "surface_hydrographique"();
SELECT AddGeometryColumn('surface_hydrographique','geometrie',2154,'GEOMETRY',3);
CREATE INDEX "surface_hydrographique_geometrie_geom_idx" ON "surface_hydrographique" USING GIST ("geometrie");
ALTER TABLE "surface_hydrographique" ADD COLUMN "cleabs" VARCHAR(24);
ALTER TABLE "surface_hydrographique" ADD COLUMN "code_hydrographique" VARCHAR(19);
ALTER TABLE "surface_hydrographique" ADD COLUMN "code_du_pays" VARCHAR(8);
ALTER TABLE "surface_hydrographique" ADD COLUMN "nature" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "position_par_rapport_au_sol" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "etat_de_l_objet" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "date_creation" timestamp with time zone;
ALTER TABLE "surface_hydrographique" ADD COLUMN "date_modification" timestamp with time zone;
ALTER TABLE "surface_hydrographique" ADD COLUMN "date_d_apparition" date;
ALTER TABLE "surface_hydrographique" ADD COLUMN "date_de_confirmation" date;
ALTER TABLE "surface_hydrographique" ADD COLUMN "sources" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "identifiants_sources" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "precision_planimetrique" NUMERIC(5,1);
ALTER TABLE "surface_hydrographique" ADD COLUMN "precision_altimetrique" NUMERIC(5,1);
ALTER TABLE "surface_hydrographique" ADD COLUMN "mode_d_obtention_des_coordonnees" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "mode_d_obtention_de_l_altitude" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "statut" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "persistance" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "salinite" BOOLEAN;
ALTER TABLE "surface_hydrographique" ADD COLUMN "origine" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "commentaire_sur_l_objet_hydro" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "liens_vers_plan_d_eau" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "liens_vers_cours_d_eau" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "lien_vers_entite_de_transition" VARCHAR(24);
ALTER TABLE "surface_hydrographique" ADD COLUMN "cpx_toponyme_de_plan_d_eau" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "cpx_toponyme_de_cours_d_eau" VARCHAR;
ALTER TABLE "surface_hydrographique" ADD COLUMN "cpx_toponyme_d_entite_de_transition" VARCHAR;

